name: Android Build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'

      - name: Permission
        run: chmod +x gradlew

      - name: Build Gradle
        run: ./gradlew build

      - name: Build Release APK
        run: bash ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.1
          files: app/build/outputs/apk/debug/app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}